site_name: Droughtwatch Capstone Project
repo_url: https://github.com/SergeiOssokine/droughtwatch_capstone
nav:
  - "Home": index.md
  - 'User Guide':
    - User Guide: "user_guide/user_guide.md"
    - Training pipeline in detail: "user_guide/training_pipeline.md"
    - Inference pipeline in detail: "user_guide/inference_pipeline.md"
  - 'Python API':
    - Training module: "python_docs/python_docs_training.md"
    - Inference module: "python_docs/python_docs_inference.md"

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google