site_name: Droughtwatch Capstone Project
nav:
  - "Home": index.md
  - 'User Guide':
    - User Guide: "user_guide/user_guide.md"
    - Training pipeline in detail: "user_guide/training_pipeline.md"
  - 'Python API':
    - Training module: "python_docs/python_docs_training.md"
    - Inference module: "python_docs/python_docs_inference.md"
theme:
  name: material
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google