[tool.pylint.messages_control]
disable = [
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods",
    "logging-fstring-interpolation"
]
[tool.pylint.main]
ignore-paths = ["^.mlops/.*"]

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
