services:
    postgres:
        image: postgres:13
        env_file:
            - .env
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5
        restart: always

    scheduler:
        build: .
        command: scheduler
        restart: on-failure
        user: "root"
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ../training/airflow/:/usr/local/airflow
            - ./scripts:/usr/local/airflow/scripts
        deploy:
            resources:
                limits:
                    memory: 12GB
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
                    memory: 8GB

    webserver:
        build: .
        entrypoint: /usr/local/airflow/scripts/entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ../training/airflow/:/usr/local/airflow
            - ./scripts:/usr/local/airflow/scripts

        user: "root"
        ports:
            - "8080:8080"
        healthcheck:
            test: [ "CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]" ]
            interval: 30s
            timeout: 30s
            retries: 3

    mlflow:	
      build:
        context: .
        dockerfile: mlflow.dockerfile
      ports:
        - 5012:5012
      volumes:
        - "${PWD}/../training/airflow/mlflow:/home/mlflow/"
volumes:
  postgres-db-volume: