name: CI-Tests
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'setup/**'
      - 'tests/**'

env:
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: 'foo'
  AWS_SECRET_ACCESS_KEY: 'bar'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: setup
        run: pip install uv && uv pip install --system --no-cache   -r dev_requirements.txt

      - name: Run Unit tests
        run: |
          make integration_tests